name: CI/CD

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
  
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
        
      - name: Download deps
        run: npm install --legacy-peer-deps
        
      - name: Run tests
        run: npm run test

